### PR TITLE
Fix error thrown by yargs on invalid argument and option

### PR DESCRIPTION
**Pull request by MartinMinkov**
**Description**:

When using an unknown command, `strict()` will catch the command being wrong but when specifying a wrong command with an option, yargs will throw an error related to https://github.com/o1-labs/snapp-cli/issues/77

To fix this, we remove the `strict()` option and add `strictCommands()` and `strictOptions()`. `strictCommands()` is similar to `strict()` that it applies to unrecognized commands but we also add `strictOptions()` to catch unrecognized options as well. This makes the `snapp-cli` not throw an error when an invalid argument and an invalid option are passed together. 

**Tested**
Manually tested by specifying wrong commands and options.

**Output**
```
$ snapp-cli foo
Usage: snapp <command> [options]

Commands:
  snapp project [name]  Create a new project                  [aliases: proj, p]
  snapp file [name]     Create a new file & test                    [aliases: f]
  snapp example [name]  Create an example project                   [aliases: e]
  snapp system          Show system info                       [aliases: sys, s]

Options:
  -h, --help     Show help                                             [boolean]
  -v, --version  Show version number                                   [boolean]



    █▄ ▄█ █ █▄ █ ▄▀▄
    █ ▀ █ █ █ ▀█ █▀█

     MINA Protocol
      

Unknown command: foo
```
```
$ snapp-cli foo bar
Usage: snapp <command> [options]

...

Unknown commands: foo, bar
```
```
$ snapp-cli project foobar
✔ Fetch project template
✔ Initialize Git repo
✔ NPM install
✔ Set project name
✔ Git init commit

Success!

Next steps:
  cd foobar
  git remote add origin <your-repo-url>
  git push -u origin main
```

### CODE REVIEW

**Comment by jasongitmail** [comment]
Could using [`.fail()`](https://yargs.js.org/docs/#fail) achieve the intent of this PR as well? I haven't dug into it to confirm

**Comment by MartinMinkov** [comment]
> Could using yarg's [`.fail()`](https://yargs.js.org/docs/#fail) achieve the intent of this PR as well? I haven't dug into it to confirm

`fail()` does not work for correcting the behavior outlined in https://github.com/o1-labs/snapp-cli/issues/77 unfortunately :/

**Review by jasongitmail — APPROVED** [review]
Oh great! You found a cleaner way to do this than try/catch. Looks good! LGTM

**Comment by jasongitmail** [comment]
Can you squash & merge this one when you do please? For a cleaner history

**Pull request merged**
